# Generated by Django 2.1.7 on 2019-02-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('calle', models.CharField(max_length=30)),
                ('exterior', models.CharField(max_length=10)),
                ('interior', models.CharField(max_length=15)),
                ('fraccionamiento', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('entidad', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
