# Generated by Django 2.2.2 on 2019-06-25 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodegas',
            options={'verbose_name_plural': 'Bodegas'},
        ),
    ]
