# Generated by Django 2.1.7 on 2019-02-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=12)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.FloatField()),
                ('peso', models.FloatField()),
                ('ancho', models.FloatField()),
                ('alto', models.FloatField()),
                ('profundidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Bodegas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacion.Item')),
            ],
        ),
    ]
