# Generated by Django 2.1.7 on 2019-02-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('relacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Movimiento')),
                ('movimiento', models.CharField(max_length=10)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Bodegas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacion.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
