# Generated by Django 2.1.7 on 2019-02-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0002_auto_20190221_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnSal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mov', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relacion.EnSal'),
        ),
    ]
